#include <err.h>
#include <openssl/bio.h>
#include <openssl/err.h>
#include <openssl/ssl.h>
#include <stdint.h>
#include <stdio.h>
#include <uv.h>

// LIBUV
#define DEFAULT_BACKLOG 1
// OPENSSL

void on_connection_close(uv_handle_t* handle);
void on_sigint_received(uv_signal_t* handle, int sig);
void on_new_connection(uv_stream_t* server, int status);
void close_uv_loop(uv_loop_t* loop);
void ssl_init(const char* certsfile, const char* keyfile);

void on_alloc(uv_handle_t* handle, size_t suggested_size, uv_buf_t* buf);
// struct write_req_t {
//     uv_write_t req;
//     uv_buf_t wbuf;
// };
void print_decrypted_data(const char* buf, const size_t len) {
    printf("decrypted data: %.s\n", len, buf);
    // const char* str = "hello!";
    // client.queue_write(str, sizeof(str));
}

class SSLClient {
    // public: // TEMPORARY
    SSL* ssl;
    BIO *rbio, *wbio;

    struct buf_t {
        char* buf = nullptr;
        size_t len;
        // TODO: make forward_list here
        void queue_data(const char* data, const size_t n){
            if (buf == nullptr)
                buf = (char*)malloc(len+n);
            else
                buf = (char*)realloc(buf, len+n);
            memcpy(buf+len, data, n);
            len += n;
        }
    };
    buf_t* to_encrypt_buf = new buf_t(); // data waiting to be encrypted by SSL
    buf_t* to_write_buf = new buf_t(); // data generated by SSL and waiting to be written to socket

    /// @brief on decrypted data available
    /// @param out buffer to write. sizeof(out) <= n unencrypted bytes
    void (*on_decrypted_cb)(const char* out, const size_t len);


    enum class SSLStatus {
        OK, WANT_IO, FAIL
    };
    static SSLStatus get_ssl_status(SSL* ssl, int n) {
        switch (SSL_get_error(ssl, n)) {
            case SSL_ERROR_NONE:
                return SSLStatus::OK;
            case SSL_ERROR_WANT_WRITE:
            case SSL_ERROR_WANT_READ:
                return SSLStatus::WANT_IO;
            case SSL_ERROR_ZERO_RETURN:
            case SSL_ERROR_SYSCALL:
            default:
                return SSLStatus::FAIL;
        }
    }

    /// @brief process data: to_encrypt_buf -> SSL encryption -> to_write_buf
    /// @return true on fail
    bool do_encrypt(){
        while (to_encrypt_buf->len > 0){
            int n = SSL_write(ssl, to_encrypt_buf->buf, to_encrypt_buf->len);
            // there are data to encrypt
            if (n > 0){
                // move remaining after SSL_write bytes to begin of the to_encrypt_buf
                if (n < to_encrypt_buf->len)
                    memmove(to_encrypt_buf->buf, to_encrypt_buf->buf+n, to_encrypt_buf->len-n);
                to_encrypt_buf->len -= n;
                // free empty memory
                to_encrypt_buf->buf = (char*)realloc(to_encrypt_buf->buf, to_encrypt_buf->len);

                // write data to the to_write_buf
                char buf[256];
                do {
                    n = BIO_read(wbio, buf, sizeof(buf));
                    if (n > 0)
                        to_write_buf->queue_data(buf, n);
                    else if (!BIO_should_retry(wbio))
                        return true;
                } while (n > 0);
            }
            // end of to_encrypt_buf;
            if (n == 0) break;
        }
        return 0;
    }


    
public:
    
    SSLClient(SSL_CTX* ctx, void (*on_decrypted_cb)(const char* out, const size_t len)) {
        rbio = BIO_new(BIO_s_mem());
        wbio = BIO_new(BIO_s_mem());
        ssl = SSL_new(ctx);
        SSL_set_accept_state(ssl); /* ??? (c) example: sets ssl to work in server mode. */
        SSL_set_bio(ssl, rbio, wbio);

        this->on_decrypted_cb = on_decrypted_cb;
    }

    /// @brief do SSL handshake
    /// @return SSLStatus::OK - handshake done.
    SSLStatus do_handshake() {
        int n = SSL_do_handshake(ssl);
        if (get_ssl_status(ssl, n) == SSLStatus::WANT_IO) {
            char buf[256];
            do {
                n = BIO_read(wbio, buf, sizeof(buf));
                printf("n: %d\n", n);
                if (n > 0)
                    to_write_buf->queue_data(buf, n);
                else if (n == 0)
                    return SSLStatus::WANT_IO;
                else if (!BIO_should_retry(wbio))
                    return SSLStatus::FAIL;
            } while (n > 0);
        }
        return SSLStatus::OK;
    }

    /// @brief encrypt and write data
    /// @param in unencrypted input
    /// @param len size of *in
    void queue_write(const char* in, const size_t len){
        to_encrypt_buf->queue_data(in, len);
    }

    

    ~SSLClient(){
        SSL_free(ssl);
        free(to_write_buf);
        free(to_encrypt_buf);
    }

    static void on_read_after_handshake(uv_stream_t* client, ssize_t nread,
                                        const uv_buf_t* rbuf) {
        // if OK
        if (nread > 0) {
            SSLClient& ssl_client = *static_cast<SSLClient*>(client->data);
            char* p_data = rbuf->base;
            while (nread > 0) {
                // pass data
                int n = BIO_write(ssl_client.rbio, p_data, nread);
                if (n <= 0) return;  // on BIO error
                p_data += n;
                nread -= n;

                // try decoding
                do {
                    char buf[256];
                    n = SSL_read(ssl_client.ssl, buf, sizeof(buf));
                    // call user callback
                    if (n > 0)
                        ssl_client.on_decrypted_cb(buf, n);
                } while (n > 0);
                SSLStatus ret = get_ssl_status(ssl_client.ssl, n);
                if (ret == SSLStatus::WANT_IO){
                    do {
                        char buf[256];
                        n = BIO_read(ssl_client.wbio, buf, sizeof(buf));
                        if (n > 0)
                            ssl_client.to_write_buf->queue_data(buf, n);
                        else if (!BIO_should_retry(ssl_client.wbio))
                            return;
                    } while (n > 0);
                }
            }
        }
        // if ERROR
        if (nread < 0) {
            warnx("nread < 0");
            if (nread != UV_EOF)
                warnx("read error (%ld) %s", nread, uv_err_name(nread));
            uv_close((uv_handle_t*)client, on_connection_close);
        }
        // if nread <= 0
        free(rbuf->base);
    }
    static void on_read_before_handshake(uv_stream_t* client, ssize_t nread,
                                  const uv_buf_t* rbuf) {
        // if OK
        if (nread > 0) {
            SSLClient& ssl_client = *static_cast<SSLClient*>(client->data);
            char* p_data = rbuf->base;
            while (nread > 0){
                // pass data
                int n = BIO_write(ssl_client.rbio, p_data, nread);
                if (n <= 0) return; // on BIO error
                p_data += n;
                nread -= n;

                // try handshake
                switch (ssl_client.do_handshake()) {
                    case SSLStatus::WANT_IO:
                        continue;
                    case SSLStatus::FAIL:
                        warnx("ssl handshake failed");
                        return;
                    case SSLStatus::OK:
                        printf("%d\n", uv_read_stop(client));
                        printf("%d\n", uv_read_start((uv_stream_t*)client, on_alloc,
                                      on_read_after_handshake));
                }
            }
        }
        // if ERROR
        if (nread < 0){
            warnx("nread < 0");
            if (nread != UV_EOF)
                warnx("read error (%ld) %s", nread, uv_err_name(nread));
            uv_close((uv_handle_t*)client, on_connection_close);
        }
        // if nread <= 0
        free(rbuf->base);
    }
};

SSL_CTX *ssl_context = nullptr;
int main(){
    uv_loop_t* main_loop = uv_default_loop();

    uv_signal_t sigint;
    uv_signal_init(main_loop, &sigint);
    uv_signal_start(&sigint, on_sigint_received, SIGINT);

    ssl_init("server.crt", "server.key");

    uv_tcp_t server;
    uv_tcp_init(main_loop, &server);
    struct sockaddr_in addr;
    uv_ip4_addr("0.0.0.0", 20202, &addr);
    uv_tcp_bind(&server, (const struct sockaddr*)&addr, 0);
    int r = uv_listen((uv_stream_t*)&server, DEFAULT_BACKLOG, on_new_connection);
    if (r) {
        warnx("tcp listen error %s (%d)", uv_strerror(r));
        return 1;
    }

    printf("running the loop\n");
    int exit_code = uv_run(main_loop, UV_RUN_DEFAULT);


    printf("the loop is over (%d)", exit_code);
    // free(main_loop); // dont free the default loop
    main_loop = nullptr;
    return exit_code;
}

void _on_uv_walk(uv_handle_t* handle, void* arg) { uv_close(handle, NULL); }
void full_close_uv_loop(uv_loop_t* loop) {
    // close all handlers first
    uv_stop(loop);
    uv_walk(loop, _on_uv_walk, NULL);
    uv_run(loop, UV_RUN_DEFAULT);  // run loop one time
    // close the loop
    uv_loop_close(loop);
}
void on_sigint_received(uv_signal_t* handle, int sig) {
    printf("received signal %d\n", sig);
    full_close_uv_loop(handle->loop);
}

void on_alloc(uv_handle_t* handle, size_t suggested_size, uv_buf_t* buf) {
    buf->base = (char*)malloc(suggested_size);
    buf->len = suggested_size;
}

void on_new_connection(uv_stream_t* server, int status){
    if (status < 0){
        warnx("connection accept error (%d) %s", status, uv_strerror(status));
        return;
    }
    uv_tcp_t* client = (uv_tcp_t*)malloc(sizeof(uv_tcp_t));
    uv_tcp_init(server->loop, client);
    if (uv_accept(server, (uv_stream_t*)client) == 0){
        printf("new client\n");
        SSLClient* ssl_client = new SSLClient(ssl_context, print_decrypted_data);
        client->data = ssl_client;
        uv_read_start((uv_stream_t*) client, on_alloc, SSLClient::on_read_before_handshake);
    }
}
void on_connection_close(uv_handle_t* handle) {
    printf("client disconnected\n");
    delete (SSLClient*)handle->data;
    free(handle);
}

void ssl_init(const char* certsfile, const char* keyfile) {
    SSL_library_init();
    OpenSSL_add_all_algorithms();
    const unsigned char session_cache_id[] = "SSL_TEST_01_VERSIYA";
    ssl_context = SSL_CTX_new(TLS_server_method());
    if (ssl_context == nullptr) {
        ERR_print_errors_fp(stderr);
        errx(EXIT_FAILURE, "Failed to create server SSL_CTX");
    }
    // configure SSL_CTX
    if (!SSL_CTX_set_min_proto_version(ssl_context, TLS1_3_VERSION)) {
        SSL_CTX_free(ssl_context);
        ERR_print_errors_fp(stderr);
        errx(EXIT_FAILURE,
             "Failed to set the minimum TLS protocol version (hardcoded "
             "TLS1.3)");
    }
    uint64_t opts = 0;
    opts |= SSL_OP_IGNORE_UNEXPECTED_EOF;
    opts |= SSL_OP_NO_RENEGOTIATION;
    opts |= SSL_OP_CIPHER_SERVER_PREFERENCE;
    opts |= SSL_OP_ALL | SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3;
    SSL_CTX_set_options(ssl_context, opts);
    if (SSL_CTX_use_certificate_chain_file(ssl_context, certsfile) <= 0) {
        SSL_CTX_free(ssl_context);
        ERR_print_errors_fp(stderr);
        errx(EXIT_FAILURE, "Failed to load the server certificate chain file");
    }
    if (SSL_CTX_use_PrivateKey_file(ssl_context, keyfile, SSL_FILETYPE_PEM) <= 0) {
        SSL_CTX_free(ssl_context);
        ERR_print_errors_fp(stderr);
        errx(EXIT_FAILURE,
             "Error loading the server private key file, "
             "possible key/cert mismatch???");
    }
    // Enable SSL_SESSION caching
    SSL_CTX_set_session_id_context(ssl_context, session_cache_id,
                                   sizeof(session_cache_id));
    SSL_CTX_set_session_cache_mode(ssl_context, SSL_SESS_CACHE_SERVER);
    // How many client TLS sessions to cache.
    // The default is 20k (SSL_SESSION_CACHE_MAX_SIZE_DEFAULT)
    SSL_CTX_sess_set_cache_size(ssl_context, 64);
    // t in seconds. the default is two hours
    SSL_CTX_set_timeout(ssl_context, 3600);

    // Explicitly disable clients sertificate store
    SSL_CTX_set_verify(ssl_context, SSL_VERIFY_NONE, NULL);
}